// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezzpvasnitpqabsssktm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6enB2YXNuaXRwcWFic3Nza3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzI0NTMsImV4cCI6MjA2MzkwODQ1M30.P22uZj5vh6TW6eZmoAYmLjust7Cjaj0uW20dDsxVC6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);